---
# Source: ingressmonitorcontroller/templates/role.yaml

---
# Source: ingressmonitorcontroller/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: ingressmonitorcontroller
    
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-v1.0.66"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    version: v1.0.66
    
    group: com.stakater.platform
    provider: stakater
    
  name: ingressmonitorcontroller
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ingressmonitorcontroller
      release: "RELEASE-NAME"
      group: com.stakater.platform
      provider: stakater
      
  template:
    metadata:
      labels:
        app: ingressmonitorcontroller
        chart: "ingressmonitorcontroller-v1.0.66"
        release: "RELEASE-NAME"
        heritage: "Tiller"
        version: v1.0.66
        
        group: com.stakater.platform
        provider: stakater
        
    spec:
      containers:
      - env:
        - name: CONFIG_FILE_PATH
          value: /etc/IngressMonitorController/config.yaml
        image: "stakater/ingressmonitorcontroller:v1.0.66"
        imagePullPolicy: IfNotPresent
        name: ingressmonitorcontroller
        volumeMounts:
        - mountPath: /etc/IngressMonitorController
          name: config-volume
      serviceAccountName: ingressmonitorcontroller
      volumes:
      - configMap:
          name: ingressmonitorcontroller
        name: config-volume

---
# Source: ingressmonitorcontroller/templates/clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingressmonitorcontroller-role
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "route.openshift.io"
    resources:
      - ingresses
      - routes
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - list
      - get
      - watch
---
# Source: ingressmonitorcontroller/templates/rolebinding.yaml

---
# Source: ingressmonitorcontroller/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ingressmonitorcontroller
    version: 1.0.46
    group: com.stakater.platform
    provider: stakater
    chart: "ingressmonitorcontroller-1.0.46"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: ingressmonitorcontroller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingressmonitorcontroller-role
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "route.openshift.io"
    resources:
      - ingresses
      - routes
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - list
      - get
      - watch
---
# Source: ingressmonitorcontroller/templates/clusterrolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ingressmonitorcontroller-role-binding
roleRef:
  kind: ClusterRole
  name: ingressmonitorcontroller-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: ingressmonitorcontroller
  namespace: default
---
# Source: ingressmonitorcontroller/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingressmonitorcontroller
  annotations:
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-v1.0.66"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    version: v1.0.66
    
    group: com.stakater.platform
    provider: stakater
    
data:
  config.yaml: |-
    providers:
    - name: UptimeRobot
      apiKey: your-api-key
      apiURL: https://google.com
      username: null
      password: null
      accountEmail: null
      alertContacts: some-alert-contacts
    enableMonitorDeletion: true
    monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"

---
# Source: ingressmonitorcontroller/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-v1.0.66"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    version: v1.0.66
    
    group: com.stakater.platform
    provider: stakater
    
  name: ingressmonitorcontroller
